<a href="https://colab.research.google.com/github/KeshavGoyal-dot/UCS420-Cognitive-Computing/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [1]:
import numpy as np

arr=np.array([10,20,30,40,50])
print("Original array:",arr)

addition=arr+2
print("After adding 2:",addition)

multiplication=arr*3
print("After multiplying 2:",multiplication)

division=arr/2
print("After dividing 2:",division)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying 2: [ 30  60  90 120 150]
After dividing 2: [ 5. 10. 15. 20. 25.]


Q2

In [2]:
arr2=np.array([1,2,3,6,5,4])
reversed_arr=arr2[::-1]

print("Original array:",arr2)
print("Reversed array:",reversed_arr)

Original array: [1 2 3 6 5 4]
Reversed array: [4 5 6 3 2 1]


In [4]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
values,count=np.unique(x,return_counts=True)

most_frequent_x=values[np.argmax(count)]
indices_x=np.where(x==most_frequent_x)

print("x=",x)
print("The most frequent value in the array is:",most_frequent_x)
print("indices:",indices_x[0])



y=np.array([1,1,1,2,3,4,2,4,3,3,3])
values,count=np.unique(y,return_counts=True)

most_frequent_y=values[np.argmax(count)]
indices_y=np.where(y==most_frequent_y)

print("y=",y)
print("The most frequent value in the array is:",most_frequent_y)
print("indices:",indices_y[0])

x= [1 2 3 4 5 1 2 1 1 1]
The most frequent value in the array is: 1
indices: [0 5 7 8 9]
y= [1 1 1 2 3 4 2 4 3 3 3]
The most frequent value in the array is: 3
indices: [ 4  8  9 10]


Q3

In [5]:
arr3=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("2-D array:")
print(arr3)

print("1st row, 2nd column:",arr3[0,1])

print("3rd row, 1st column:",arr3[2,0])

2-D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


Q4

In [7]:
Keshav=np.linspace(10,100,25)

print("array:")
print(Keshav)

print("dimensions (ndim):",Keshav.ndim)

print("Shape:",Keshav.shape)

print("Total elements (size):",Keshav.size)

print("Data Type:",Keshav.dtype)

print("Total bytes consumed (nbytes):",Keshav.nbytes)

print("transposse of 1-D array:")
print(Keshav.T)

column_array=Keshav.reshape(25,1)

print("Reshaped as column:")
print(column_array)

print("Transpose of column_array:")
print(column_array.T)

array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data Type: float64
Total bytes consumed (nbytes): 200
transposse of 1-D array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Reshaped as column:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose of column_array:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


Q5

In [8]:
ucs420_Keshav=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])
print("Original 2-D array:")
print(ucs420_Keshav)

print("Mean:",np.mean(ucs420_Keshav))

print("Median:",np.median(ucs420_Keshav))

print("Maximum:",np.max(ucs420_Keshav))

print("Minimum:",np.min(ucs420_Keshav))

print("Unique elements:",np.unique(ucs420_Keshav))

reshaped_ucs420_Keshav=ucs420_Keshav.reshape(4,3)
print("Reshaped array (4*3):")
print(reshaped_ucs420_Keshav)

resized_ucs420_keshav=np.resize(ucs420_Keshav,(2,3))
print("Resized array (2*3):")
print(resized_ucs420_keshav)

Original 2-D array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array (4*3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2*3):
[[10 20 30]
 [40 50 60]]
